// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSU8dYsNt7EpaP_2SNDNL9cTvUkDhUH8U',
    appId: '1:980547760636:web:3290b0ce30ed4d40fbc279',
    messagingSenderId: '980547760636',
    projectId: 'test-multifactor-auth',
    authDomain: 'test-multifactor-auth.firebaseapp.com',
    storageBucket: 'test-multifactor-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5FF8vWpQOHOdpqWPYrsxao1s_FBqmaLo',
    appId: '1:980547760636:android:ad66c9b76b81bf80fbc279',
    messagingSenderId: '980547760636',
    projectId: 'test-multifactor-auth',
    storageBucket: 'test-multifactor-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpIRFPfAufEm919LY0uHGmez9VBESZbFM',
    appId: '1:980547760636:ios:f8af66f451de3aaefbc279',
    messagingSenderId: '980547760636',
    projectId: 'test-multifactor-auth',
    storageBucket: 'test-multifactor-auth.appspot.com',
    iosBundleId: 'com.example.testMultifactorAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpIRFPfAufEm919LY0uHGmez9VBESZbFM',
    appId: '1:980547760636:ios:c26aaacd140f3494fbc279',
    messagingSenderId: '980547760636',
    projectId: 'test-multifactor-auth',
    storageBucket: 'test-multifactor-auth.appspot.com',
    iosBundleId: 'com.example.testMultifactorAuth.RunnerTests',
  );
}
